import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import Layout from '../Components/Layout/Layout.tsx'
import { fetchCars } from '../Components/store/features/Cars_thunk'


export default function Home() {
  const arr = useSelector(state => state.data)
  const dispatch = useDispatch()

  useEffect(() => {
    if (arr.length === 0) {
      dispatch(fetchCars())
    }
  }, [])

  return (
    <Box maxW={'1920px'} h={'100%'} display={'flex'} flexDirection={'column'} position={'relative'}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        Main
      </Layout>
    </Box>
  )
}