import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import { useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { fetchCars } from '../Components/store/features/Cars_thunk'

export default function Home() {
  const arr = useSelector(state => state.data)
  const dispatch = useDispatch()

  useEffect(() => {
    if (arr.length === 0) {
      dispatch(fetchCars())
    }
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Box></Box>
    </div>
  )
}